### ISSUE TITLE
pip cannot install pyonmttok on Windows

### ISSUE THREAD

**Issue by aastha19** [OpenNMT/Tokenizer#118]
Installing via pip in Windows results in Error

![image](https://user-images.githubusercontent.com/14852345/67853603-ee83d880-fb34-11e9-9b8a-1bda3dcf7f93.png)

**Comment by guillaumekln** [comment]
Unfortunately we don't build and publish packages for Windows. We don't have the infrastructure for that at the moment.

**Comment by aastha19** [comment]
![image](https://user-images.githubusercontent.com/14852345/67854149-d3fe2f00-fb35-11e9-941c-95f3659234c2.png)

Then why is the command in your README.md 
This command doesn't work in both windows and Ubuntu.

**Comment by guillaumekln** [comment]
It works on Ubuntu (and Linux in general).

**Comment by aastha19** [comment]
working fine in Ubuntu. Thanks
