### ISSUE TITLE
multiple joiner annotate with spm model

### ISSUE THREAD

**Issue by Zenglinxiao** [OpenNMT/Tokenizer#124]
Hello, I just find that if we use a sentencepiece model with `--joinner_annotate` on, we may get double joiner between two token.

`/tokenize --mode none --sp_model en_ja.spm.model --joiner_annotate`
```
Vocab: [`mag`, `ne`, `tic`, `)`, `,`]
phrase: `｟_ph_5｠magnetic field ｟_ph_6｠)`, `｟_ph_2｠,`
phrase tokenized: `｟_ph_5｠￭ ￭mag ￭ne ￭tic field ｟_ph_6｠ ￭ ￭)`, `｟_ph_2｠￭ ￭,`
```
And if we enable tokenize with mode conservative/aggressive, we get more these example for punctuation, like:
```
phrase:  `depending on its temperature.`
phrase tokenized: `depend ￭ing on its temperature ￭ ￭.`
```
* Notice that: the sentencepiece model is trained in tokenizer `--mode none`

My question is: Are these behavior correct?

**Comment by guillaumekln** [comment]
No, we don't expect two consecutive joiners. Thanks for reporting.

I can reproduce the behavior with one SentencePiece model I have around, but it does not happen with all. I will re-check the implemented logic.

**Comment by guillaumekln** [comment]
Looks like it happens when SentencePiece does not attach the leading spacer to the first subtoken, e.g.:

```
$ echo "crumpled" | cli/tokenize --mode none --sp_model ~/data/wmt_ende_sp/wmtende.model
▁ cru mpl ed

$ echo "｟_ph_5｠crumpled" | cli/tokenize --mode none --sp_model ~/data/wmt_ende_sp/wmtende.model
｟_ph_5｠ cru mpl ed

$ echo "｟_ph_5｠crumpled" | cli/tokenize --mode none --sp_model ~/data/wmt_ende_sp/wmtende.model --joiner_annotate
｟_ph_5｠￭ ￭cru ￭mpl ￭ed
```

but the most common pattern will work:

```text
$ echo "prose" | cli/tokenize --mode none --sp_model ~/data/wmt_ende_sp/wmtende.model 
▁pro se

$ echo "｟_ph_5｠prose" | cli/tokenize --mode none --sp_model ~/data/wmt_ende_sp/wmtende.model --joiner_annotate
｟_ph_5｠￭ pro ￭se
```
