### ISSUE TITLE
pyonmttok.Tokenizer accept callback function ?

### ISSUE THREAD

**Issue by Zenglinxiao** [OpenNMT/Tokenizer#125]
I just wondering if we could make the Tokenizer accept also a callback function as a pretokenizer.

This will benefit a lot especially for CJK languages which do not have whitespace as word separator.
And also for the case of using combination of different pretokenizer, as:
` def pretok(sent): return jieba_tok(onmt_tok(sent))`

**Comment by guillaumekln** [comment]
Could you give an example to specify when exactly the callback function should be called?

**Comment by Zenglinxiao** [comment]
Like these:
```python
>>> def pretok_fn(sentence):
...:    zh_seg = pkuseg.pkuseg()
...:    tok = zh_seg.cut(sentence)
...:    return ' '.join(tok)
>>> onmtpretokenizer = pyonmttok.Tokenizer('none', pretok=pretok_fn, **other_opts)
>>> tokens, _ = onmtpretokenizer.tokenize('Hello World, 测试中文分词!')
>>> tokens
['Hello', 'World', '￭,', '测试', '￭中文', '￭分词' '￭!']

>>> learner = pyonmttok.SentencePieceLearner(tokenizer=onmtpretokenizer, **other_opts)
>>> learner.ingest_file(data_path)
>>> tokenizer = learner.learn(model_path)
>>> tokenizer.tokenize_file(filename, outname, num_threads)
```

**Comment by guillaumekln** [comment]
The main issue is that we are quickly out of the Python territory.

It seems you could achieve this with [`support_prior_joiners`](https://github.com/OpenNMT/Tokenizer/blob/master/docs/options.md#support_prior_joinersboolean-default-false):

1. Pre-tokenize the file with the custom tool and integrate joiners
2. Define the tokenizer: `pyonmttok.Tokenizer('none', support_prior_joiners=True, **other_opts)`
3. Ingest the pre-tokenized file

**Comment by guillaumekln** [comment]
I think the new [Token API](https://github.com/OpenNMT/Tokenizer/tree/master/bindings/python#token-api) can also help you apply a pretokenization. For example, you can update the pretokenization function to produce `Token` objects that you further tokenize with a `Tokenizer` instance. The Token API helps you forward properties of the initial tokens (left/right joiner) to the final tokens.

Consider the following example:

```python
import pyonmttok
import itertools

pre_tokens = [pyonmttok.Token("Hello"), pyonmttok.Token("World"), pyonmttok.Token("!", join_left=True)]
tokenizer = pyonmttok.Tokenizer("none", sp_model_path="sp.model")

def retokenize(token):
    subwords = tokenizer.tokenize(token.surface, as_token_objects=True)
    subwords[0].join_left = token.join_left
    subwords[-1].join_right = token.join_right
    return subwords

subwords = list(itertools.chain.from_iterable(map(retokenize, pre_tokens)))
tokens, _ = tokenizer.serialize_tokens(subwords)
print(tokens)
```

```bash
$ python pretok.py
['▁H', 'ello', '▁World', '!']
```

Subword learners also have an `ingest_token` method that accepts `Token` objects.

Let me close this issue as I think there are ways to implement pre-tokenization. Feel free to reopen if you think something is missing in the library (or not working).
