### ISSUE TITLE
Memory leak when using python wrapper?

### ISSUE THREAD

**Issue by francoishernandez** [OpenNMT/Tokenizer#130]
Hey @guillaumekln 
We stumbled upon a strange behavior using `pyonmttok`.

When building a `pyonmttok.Tokenizer` several times, it appears memory usage is increasing. Even when deleting the object (and calling `gc.collect()`) before recreating the new one.
Use case is OpenNMT-py REST server, where it happens that tokenizers can be rebuilt when loading the model. Easy fix in our case is to build the tokenizer once and for all, but I figure this is worth to be flagged.

To reproduce:
```
import pyonmttok
import time
import gc

params = {
    "bpe_model_path": "<SOME_BPE_MODEL>",
    "joiner_annotate": True,
    "joiner_new": False,
    "preserve_placeholders": True
}

for i in range(1000):
    print(i)
    tokenizer = pyonmttok.Tokenizer(mode="aggressive", **params)
    del tokenizer
    gc.collect()
    time.sleep(0.1)
    gc.collect()
```
Memory usage increases approx. 100MB every 10 iterations.

**Comment by guillaumekln** [comment]
Hi,

Thanks for reporting. I can reproduce this when setting a BPE model.

**Comment by guillaumekln** [comment]
FYI, the regression was introduced in version 1.12.0 (May 2019) and concerned tokenizers with BPE or SentencePiece models. I will push a patch version shortly with the fix.
