### ISSUE TITLE
Unwanted behaviour with --case_feature and --joiner_annotate

### ISSUE THREAD

**Issue by francoishernandez** [OpenNMT/Tokenizer#133]
Hi @guillaumekln !
I got a strange behaviour when testing some tokenization.
Some case features get "detached" from the token (appears to be only when the token is a single joiner).

For instance:
```
echo "« Je l'achèterais probablement ۛ»" | <path_to_Tokenizer>/build/cli/tokenize --case_feature --mode conservative --joiner_annotate
```
gives
```
«￨N je￨C l￨L ￭'￭￨N achèterais￨L probablement￨L ￭ ۛ￨N ￭»￨N
```
the issue being the penultimate token and its feature **￭ ۛ￨N**.

**Comment by guillaumekln** [comment]
Hi,

Looks like "»" is preceded by an unwanted combining mark [U+06DB](https://www.compart.com/en/unicode/U+06DB). I will check how it is currently handled and see if it can be improved.

You can also consider adding a cleaning rule for this kind of characters.

**Comment by guillaumekln** [comment]
What is your version? On master, we are actually escaping the space character that is annotated by the combining mark:

```
$ echo "« Je l'achèterais probablement ۛ»" | cli/tokenize --case_feature --mode conservative --joiner_annotate
«￨N je￨C l￨L ￭'￭￨N achèterais￨L probablement￨L ￭％0020ۛ￨N ￭»￨N
```

**Comment by guillaumekln** [comment]
Let me close this issue as I think the current behavior is reasonable (i.e. escaping the space). Feel free to reopen if you think this should be handled differently.
