### ISSUE TITLE
Aggressive tokenization on hyphened strings

### ISSUE THREAD

**Issue by maria-grigorieva** [OpenNMT/Tokenizer#135]
Hi, 
I have a set of strings with hyphens. For example, 'adc-job-ac-cc7-k8s-multicluster-custom-shed-12345' 
Now it is tokenized as: [adc, '-', 'job', 'ac', 'cc7', ...] - with only one hyphen. 
Is it possible to change the tokenization method to provide the following: 
['adc', '-', 'job', '-', 'ac', '-', 'cc7', '-', ...] ?

Kind Regards,
Maria

**Comment by guillaumekln** [comment]
Hi,

How can we reproduce this with the latest version? A quick check with the translation client gives me the correct tokenization:

```text
$ echo "adc-job-ac-cc7-k8s-multicluster-custom-shed-12345" | cli/tokenize --mode aggressive
adc - job - ac - cc 7 - k 8 s - multicluster - custom - shed - 12345
```

**Comment by maria-grigorieva** [comment]
I updated pyonmttok to the latest version and now it works correctly. 
Sorry for bothering, and thanks for the quick response.

**Comment by guillaumekln** [comment]
For reference, do you know which version was impacted? I don't remember this being an issue.
