### ISSUE TITLE
Segmentation fault when using case insensitive BPE model on some Unicode characters

### ISSUE THREAD

**Issue by anderleich** [OpenNMT/Tokenizer#147]
Hi,
When tokenizing a file using the Pyhton API I get a segmentation fault error. It only happens with some sentences (encoding issues). The problem is it does not give enough information like the line number. Which encoding is using? A normal python script can read the file without problems.

**Comment by guillaumekln** [comment]
Hi,

Can you provide a way to reproduce the crash?

**Comment by anderleich** [comment]
The following sentence:

The dress worn by Anna Ewers elevates the unmistakable Versace silhouette – a corset bodice and voluminous high-low skirt.All three dresses were completely constructed and embroidered at the Versace Ate\
lier in Milan, fully respecting the sustainability principles because: "𝘛𝘩𝘦𝘳𝘦'𝘴 𝘯𝘰𝘵𝘩𝘪𝘯𝘨 𝘮𝘰𝘳𝘦 𝘨𝘭𝘢𝘮𝘰𝘳𝘰𝘶𝘴 𝘵𝘩𝘢𝘯 𝘭𝘰𝘰𝘬𝘪𝘯𝘨 𝘵𝘰𝘸𝘢𝘳𝘥𝘴 𝘵𝘩𝘦 𝘧𝘶𝘵𝘶𝘳𝘦."

**Comment by guillaumekln** [comment]
What tokenization parameters are you using? Also, what is your tokenizer version?

**Comment by anderleich** [comment]
This is my code:
```
tokenizer = pyonmttok.Tokenizer(
                                bpe_model_path=model,
                                mode="conservative",
                                joiner="￭",
                                joiner_annotate=True,
                                case_markup=True)
tokenizer.tokenize_file(input_path=input_file, output_path=output_file, num_threads=16)```

Version: pyonmttok==1.18.3

**Comment by guillaumekln** [comment]
I don't get any error when running on these examples. Can you try setting `num_threads=1`?

It would be easier for us if you can provide everything needed to reproduce the error, including the BPE model.

**Comment by anderleich** [comment]
Setting `num_threads=1` does not solve the issue.
I've already used the BPE model to tokenize other files without problems

**Comment by guillaumekln** [comment]
Can you share the BPE model and the input file?

Maybe there is an invalid character that in not showing here, because I can't reproduce any crash by copy-pasting the examples.

**Comment by anderleich** [comment]
This is the BPE model:
[codes.es-en.txt](https://github.com/OpenNMT/Tokenizer/files/4883338/codes.es-en.txt)

I cannot share the input file as it is huge.

**Comment by guillaumekln** [comment]
Now I can reproduce.

**Comment by anderleich** [comment]
Is it solved? If so, should I clone the repository or can I upgrade it via pip?

**Comment by guillaumekln** [comment]
I just pushed version 1.18.5, so you can upgrade with pip.

**Comment by anderleich** [comment]
Thanks!
