### ISSUE TITLE
Progress bar when tokenizing big file

### ISSUE THREAD

**Issue by francoishernandez** [OpenNMT/Tokenizer#150]
It's probably overkill but it would be nice to have some tqdm-like progress bar when tokenizing big files.
This could possibly be achieved by keeping track of the number of bytes handled with respect to the total size of the file in bytes.

**Comment by guillaumekln** [comment]
I don't think we will integrate something as fancy as tqdm, but maybe a verbose mode that shows a percentage every X seconds.

**Comment by guillaumekln** [comment]
The PR above simply adds a verbose mode that prints something every 100,000 lines. I think this should be enough to monitor progress.

Printing a percentage is actually not possible in the tokenization client `cli/tokenize.cc` since it reads from the standard input whose total size is unknown.
