### ISSUE TITLE
Make adjacent joiner independent when using case_markup?

### ISSUE THREAD

**Issue by francoishernandez** [OpenNMT/Tokenizer#151]
Hi,
I just stumbled upon the following behaviour.

When tokenizing with `-case_markup`, some joiners are added to the tokens adjacent to the markup. These joiners are valid, but in many cases this creates duplicates in the final vocabulary.

E.g.
Before tokenization:
```
... activos de garantía del BCE ( EligibleAssets.hotline@ecb.int ) .
```
After tokenization:
```
... activos de garantía del ｟mrk_begin_case_region_U｠ bce ｟mrk_end_case_region_U｠ ( ｟mrk_case_modifier_C｠ eligible￭ ｟mrk_case_modifier_C｠ assets ￭.￭ hotline ￭@￭ ecb ￭.￭ int ) .
```
--> "eligible" may already be in our vocabulary, but here we duplicate it with "eligible￭"

On large datasets this behaviour seems to happen quite a lot and lead to unnecessarily big vocabularies.

**Is this intentional?**

**Note:** the `-joiner_new` flag would probably prevent this, but I'm not sure it's the most appropriate way, as prior results lead us to believe it might not be the optimal setup.

**Comment by guillaumekln** [comment]
Hi,

You probably want to use [`--preserve_segmented_tokens`](https://github.com/OpenNMT/Tokenizer/blob/master/docs/options.md#preserve_segmented_tokens-boolean-default-false):

```text
$ echo "EligibleAssets" | cli/tokenize --joiner_annotate --segment_case
Eligible￭ Assets
$ echo "EligibleAssets" | cli/tokenize --joiner_annotate --segment_case --preserve_segmented_tokens
Eligible ￭ Assets
```

It should be the default, but it was added after the first release so we had to keep backward compatibility.
