### ISSUE TITLE
Reproducibility of subword regularization

### ISSUE THREAD

**Issue by Zenglinxiao** [OpenNMT/Tokenizer#168]
Hello there,
Is there a way to maintain the reproducibility when applying subword regularization (both sp & bpe)?
Something like manually set the seed after loading the model.

**Comment by guillaumekln** [comment]
Hi,

This is currently not implemented.

It should be fairly easy to support but it seems SentencePiece has no API to set a random seed.

**Comment by guillaumekln** [comment]
The latest version of SentencePiece now has a function to set a global random seed. So we can proceed with having a similar global function.

@Zenglinxiao Is it ok if the seed is global and not bound to a specific Tokenizer instance?

**Comment by Zenglinxiao** [comment]
> The latest version of SentencePiece now has a function to set a global random seed. So we can proceed with having a similar global function.
> 
> @Zenglinxiao Is it ok if the seed is global and not bound to a specific Tokenizer instance?

Yes. I'm totally fine with a global seed since that's also the way we config other packages like PyTorch, Numpy.
