### ISSUE TITLE
BPE and SentencePiece models learning

### ISSUE THREAD

**Issue by guillaumekln** [OpenNMT/Tokenizer#17]
The library should also include the required code and APIs to learn BPE and SentencePiece models.

**Comment by vince62s** [comment]
Awesome !
Guys do you confirm models for BPE and SP are 100% the same (interchangeable for the binaries) with their originlas ?

**Comment by guillaumekln** [comment]
* For SentencePiece, we simply invoke their training library so it produces the same model. The only difference is that we currently discard the generated vocabulary (can rethink that if requested).
* For BPE, the algorithm should be identical and produce the same model as the Python script (maybe @jsenellart can comment here).

Let us know how you intend to use these features. Current design is obviously driven by our own internal usage (we directly invoke the C++ APIs).
