### ISSUE TITLE
"no pair has frequency >= 2" on my entire corpus

### ISSUE THREAD

**Issue by JustCunn** [OpenNMT/Tokenizer#183]
I'm trying to apply BPE on my corpus (about 900k lines in English and Irish). When I do this with another tokenizer, Subword-NMT, it applies BPE, yet using this tokenizer it throws the error `no pair has frequency >= 2`. I'm wondering as to why it can't find those subword pairs that subword-NMT can?

Here's what I used (Python):
```
# imported package as ptk
tokenizer = ptk.Tokenizer("conservative", joiner_annotate=True)
learner = ptk.BPELearner(tokenizer=tokenizer)

learner.ingest_file("test.en")
learner.ingest_file("dev.en")
learner.ingest_file("train.en")

tokeniser = learner.learn("model_en")
```

All advice welcome

**Comment by guillaumekln** [comment]
Hi,

I tried the same code (but on another corpus) and did not get the error.

Are you using the latest version? If not, update and try again. If the error still happens, is there a way for you to share the data so that we can reproduce?

**Comment by JustCunn** [comment]
I tried running my code in a Jupyter Notebook and it ran perfectly. Might have just been an issue with using the wrong environment and I didn't notice. My bad!

Thanks for offering your help.
