### ISSUE TITLE
SetRandomGeneratorSeed’ is not a member of ‘sentencepiece’

### ISSUE THREAD

**Issue by zhouzebiao** [OpenNMT/Tokenizer#193]
When i complie the project, it occur a error：

`/root/src/Utils.cc: In function ‘void onmt::set_random_generator_seed(unsigned int)’:
/root/src/Utils.cc:66:5: error: ‘SetRandomGeneratorSeed’ is not a member of ‘sentencepiece’
     sentencepiece::SetRandomGeneratorSeed(seed);
     ^
make[2]: *** [CMakeFiles/OpenNMTTokenizer.dir/src/Utils.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/OpenNMTTokenizer.dir/all] Error 2
make: *** [all] Error 2`

**Comment by guillaumekln** [comment]
Can you run `git submodule update --init` as shown in the [README](https://github.com/OpenNMT/Tokenizer#compiling)?

**Comment by zhouzebiao** [comment]
Thanks, it solved.  It needs update third party.
