### ISSUE TITLE
Dollar sign and following number are removed during tokenization

### ISSUE THREAD

**Issue by panosk** [OpenNMT/Tokenizer#205]
The dollar sign and number following it are removed during tokenization. For instance:
`echo "The cost is only $2,300." | tokenize`
Output:
`The cost is only , 300 .`

**Comment by guillaumekln** [comment]
This is because the shell thinks `$2` is a parameter and replace it by its value (here an empty string). So the input text is actually "The cost is only ,300.".

To prevent parameter expansion you can use single quotes:

```bash
$ echo 'The cost is only $2,300.' | cli/tokenize
The cost is only $ 2,300 .
```

**Comment by panosk** [comment]
Ops, blunder. Thanks!
