### ISSUE TITLE
Compile flags for sentencepiece break compilation with MSVC

### ISSUE THREAD

**Issue by panosk** [OpenNMT/Tokenizer#219]
The following block breaks compilation with MSVC:
```CMAKE
set_target_properties(
  sentencepiece-static
  sentencepiece_train-static
  PROPERTIES COMPILE_FLAGS "-Wno-all -Wno-extra -Wno-error"
  )
```
Maybe we could use `/W0` for MSVC?

**Comment by guillaumekln** [comment]
Thanks for the report. Can you send a PR to make it work?

**Comment by panosk** [comment]
Sure, I just wanted to make sure that we disable all warnings, right?

**Comment by guillaumekln** [comment]
Yes, but just for SentencePiece targets.

**Comment by panosk** [comment]
This PR should do it, but I came across another issue with unresolved symbols when compiling the clients. I will open another issue once I gather more info.
