### ISSUE TITLE
BPE dropout deactivation for evaluation

### ISSUE THREAD

**Issue by funboarder13920** [OpenNMT/Tokenizer#232]
Hello,

Is there a way to disable the tokenizer's BPE dropout for evaluation mode ?
I don't see a how I can modify the dropout attribute or how I can call the tokenize method with a specific dropout or flag.

My current workaround is to create an evaluation specific tokenizer with 0 dropout.

Best,

**Comment by guillaumekln** [comment]
Hi,

> My current workaround is to create an evaluation specific tokenizer with 0 dropout.

Yes, it's currently the way to do it. `Tokenizer` instances are currently immutable by design.

We could think about adding a training/inference toggle, but this should work for both BPE dropout and SentencePiece sampling. Let's think about what can be done here.

**Comment by guillaumekln** [comment]
I propose to add a `training` flag to the tokenization methods `tokenize` and `tokenize_file`, e.g.:

```python
tokenizer.tokenize(text)  # current behavior
tokenizer.tokenize(text, training=False)  # disable subword regularization
```

@funboarder13920 What do you think?

**Comment by funboarder13920** [comment]
Thanks Guillaume, it's perfect.

Sorry, I didn't see your message sooner.
