### ISSUE TITLE
Potential undesirable effects with SoftCaseRegions and normalization suggestion

### ISSUE THREAD

**Issue by panosk** [OpenNMT/Tokenizer#239]
Hello,

I've been scratching my head to figure out why some sentences with all caps are properly translated while some others aren't. I think that the soft case regions create some "unseen" tokens that greatly affect translation. When translating from English, for example, the most common unseen token created by soft case regions is the pronoun "I" (as in "I ate an apple"). What happens is that almost all instances of "I" in the training corpus are in the form of `｟mrk_case_modifier_C｠i`, so when "i" appears inside a soft case region without the case modifier mark in front, it is considered "unseen".

To some extend, this can be addressed by augmenting the corpus, for example including a portion of the corpus with all caps, but IMHO it's not a clean or robust solution, as random sampling may fail to include a lot of instances of such tokens.  I don't know how effective or realistic would be to add an option to avoid or alleviate this problem after the model is built (since the user may not always know beforehand which "unseen" tokens will be created by soft case regions), something like `break_soft_case_region_on` that would let the user supply a list of words or tokens which will end the region, then the tokenizer will put the most common marker in front of the breaking token, then start a new region, etc.

Then again, I suppose we could just not use soft case regions at all, but then it looses much of its usability.

Another issue when translating sentences in all caps is accents --in most languages, words in all caps should not have accents, which unfortunately now are --sometimes-- transferred from their lowercase form. Since the ICU library is already included, maybe a normalization option could be added.

**Comment by francoishernandez** [comment]
Linked to #151? You might want to use the `preserve_segmented_tokens` flag.

**Comment by panosk** [comment]
Hi @francoishernandez ,

Thanks for your reply. 
I'm already using `preserve_segmented_tokens`, but I don't think it's closely related to #151. After some more experiments, I noticed more weird behaviors with all caps, for instance sometimes the `soft_case_region` mark is not added to the translation which means the model hasn't learnt to transfer it so the translation is not capitalized. So it seems the solution is a) augment the corpus with sentences in all caps and any necessary normalizations or b) implement a custom algorithm to always lowercase sentences in all caps, translate, convert the translation to uppercase and do any normalizations --this is actually what I was using previously, but I would prefer a consistent solution through the tokenizer if possible.

**Comment by guillaumekln** [comment]
> augment the corpus with sentences in all caps and any necessary normalizations

This should always be done, even when using `case_markup`. Otherwise, the model will not know how to deal with the uppercase region markers.

> Another issue when translating sentences in all caps is accents --in most languages, words in all caps should not have accents, which unfortunately now are --sometimes-- transferred from their lowercase form. Since the ICU library is already included, maybe a normalization option could be added.

I'm not sure why this is an issue. Can you show an example?

**Comment by panosk** [comment]
> I'm not sure why this is an issue. Can you show an example?

Sure, here it is:

Source:
`AFTER THAT, HE CAME HOME.`
Target:
`ΜΕΤΑ ΑΠΟ ΑΥΤΟ, ΓΎΡΙΣΕ ΣΠΊΤΙ.`

The words `ΓΎΡΙΣΕ ΣΠΊΤΙ` have accents, which is wrong for Greek. This can probably be fixed to a great extend by adding training examples in all caps without accents in the target side (so an extra normalization step will be required), but then another issue is likely: an unnecessary increase in the vocabulary size as there will be variations of lowercased subwords with no accents.

**Comment by guillaumekln** [comment]
Thanks. I was not aware of that. Looks like this is a common issue as ICU has a page dedicated to that: https://sites.google.com/site/icusite/design/case/greek-upper

I think it make sense to make the recasing smarter. For example, the [`text-transform`](https://developer.mozilla.org/en-US/docs/Web/CSS/text-transform) CSS rule describes some rules that are specific to some languages.

**Comment by guillaumekln** [comment]
Let me close this issue as I think the PR above fixes the main issue which was an incorrect recasing in some languages (e.g. accents should be removed in uppercase Greek).

For the other points raised in the first post, `case_markup` does not remove the need to do case-related data augmentation. It helps to simplify the vocabulary and generalize to unseen uppercase sequences, but we should still provide enough examples in uppercase or with incorrect casing for the model to learn these cases correctly.
