### ISSUE TITLE
tokenizing with a sentencepiece model gives odd results

### ISSUE THREAD

**Issue by vince62s** [OpenNMT/Tokenizer#24]
when building a SP model with vocab size 32K, tokenizing with spm_encode
gives files with about 32K tokens.

tokenizing with onmt-tok --spacer_annotate gives -s spmodel it gives more than 40-45k tokens.

either wrong usage, or something not working.

**Comment by guillaumekln** [comment]
By default, the tokenizer applies the OpenNMT tokenization (mode "conservative") so here SentencePiece is used as a subtokenizer.

For a SP only tokenization, you certainly want to use `--mode none`.

**Comment by jsenellart** [comment]
@vince62s - can you confirm that it is working as expected for you?

**Comment by vince62s** [comment]
I think it's ok now (with 1.6), but anyway, we don't use it anymore with SP.

**Comment by jsenellart** [comment]
Thanks. (btw you should 😊)

**Comment by jsenellart** [comment]
@vince62s, with last version of tokenizer sp is now compliant with placeholders
