### ISSUE TITLE
[Question] build vocab in this library ?

### ISSUE THREAD

**Issue by vince62s** [OpenNMT/Tokenizer#279]
Another question for the day:

Would that make sense for this library to be able to build a vocab (on string, batch of strings, file, list of files) with an additional parameter to set the number of lines per file for instance ?

thanks.

**Comment by guillaumekln** [comment]
I think it makes sense for this library.

My first thought would be to implement this with an interface similar to the current [subword learning API](https://github.com/OpenNMT/Tokenizer/tree/master/bindings/python#subword-learning).

> an additional parameter to set the number of lines per file for instance ?

What do you think about setting a probability parameter corresponding to the probability to consider a line for the vocabulary?

**Comment by vince62s** [comment]
in fact, and somehow related to my other point on tokenization, I think the best is to handle Iterators only (not necessarily multiple files).
for the tokenize API, I think it is similar to the torchtext one and we can get the tokenizer in the same way as this example:
```
__init__()
self.tokenizer = torchtext.data.utils.get_tokenizer('spacy', language='de_core_news_sm')
__call__()
toktext = self.tokenizer(text.rstrip("\n"))
 return toktext
```

Regarding this specific vocab thing, I found also in torchtext the good way here:
https://pytorch.org/text/stable/vocab.html#build-vocab-from-iterator
(except that I would like to avoid torchtext.)

But getting the same entry points would be great.

```
__init__()
self.transform = build_vocab_from_iterator(yield_tokens(open(textfile,'r'), lang),
                                                    min_freq=1,
                                                    specials=special_symbols,
                                                    special_first=True)
__call__()
token_ids = self.transform(tokens)
        return token_ids
```

not sure if I'm 100% clear.

**Comment by guillaumekln** [comment]
Yes, I understand the point about iterators. The only issue is that it is less efficient than a dedicated file API where everything is running on the C++ side. Of course we can provide both modes.
