### ISSUE TITLE
question related to the new features re: vocab

### ISSUE THREAD

**Issue by vince62s** [OpenNMT/Tokenizer#282]
Guillaume,
maybe I did not pay attention enough but I think there is something not 100% consistent here:

``` # Build a vocabulary from an iterator of lines.
# If a tokenizer is not set, the lines are split on spaces.
pyonmttok.build_vocab_from_lines(
    lines: Iterable[str],
    tokenizer: Optional[pyonmttok.Tokenizer] = None,
    maximum_size: int = 0,
    minimum_frequency: int = 1,
    special_tokens: Optional[List[str]] = None,
) -> pyonmttok.Vocab

# Build a vocabulary from an iterator of tokens.
pyonmttok.build_vocab_from_tokens(
    tokens: Iterable[str],
    maximum_size: int = 0,
    minimum_frequency: int = 1,
    special_tokens: Optional[List[str]] = None,
) -> pyonmttok.Vocab
```

For the second function, since it expects tokens, I think it would be better to expect Iterable[List[str]] a little bit like a detokenize function. IMO it makes more sense (on top on behaving the same way as the torchtext builb_vocab_from iterator)

what do you think ?

**Comment by vince62s** [comment]
But then it assumes that tokens are separated with spaces. I don't really see the difference between the two functions above.
When you tokenize, you return a list of tokens, not a Str.
Not a big deal, just trying to make things consistent.

**Comment by guillaumekln** [comment]
`build_vocab_from_tokens` simply takes an iterator of tokens. So each `str` in the iterator is a token, not a line.

For example, these 2 ways of creating a vocabulary are equivalent:

```python
vocab = pyonmttok.build_vocab_from_lines(lines, tokenizer)
vocab = pyonmttok.build_vocab_from_tokens(itertools.chain.from_iterable(map(tokenizer, lines)))
```

**Comment by guillaumekln** [comment]
Of course we could add another helper called `build_vocab_from_list_of_tokens` which does what you want. But it will simply be implemented with `itertools.chain.from_iterable` as shown above.

**Comment by vince62s** [comment]
no it's ok.
I'll deal with it.
