### ISSUE TITLE
save learned bpe model

### ISSUE THREAD

**Issue by rudyyin** [OpenNMT/Tokenizer#283]
How can I save the learned bpe model?

**Comment by guillaumekln** [comment]
See this example: https://github.com/OpenNMT/Tokenizer/tree/master/bindings/python#subword-learning

**Comment by rudyyin** [comment]
Thanks, I have seen the doc but don't find the api. but after seen https://opennmt.net/OpenNMT-py/examples/LanguageModelGeneration.html  I get how to save bpe model.
Maybe can add comment to learn function. 
Thanks!
