### ISSUE TITLE
speed

### ISSUE THREAD

**Issue by rudyyin** [OpenNMT/Tokenizer#284]
I have test on a machine for the tokenize speed. 
On my machine, the speed is about 2k lines per second.
But when use tokenizers from haggingface, their speed is much faster. Maybe can do some optimization?

**Comment by guillaumekln** [comment]
Can you post the exact code you are using to compare the speed?

**Comment by guillaumekln** [comment]
Without more information, we don't know what was measured and what could be improved. Feel free to reopen if you can provide more details.
