### ISSUE TITLE
step-by-step to compile from source ?

### ISSUE THREAD

**Issue by vince62s** [OpenNMT/Tokenizer#294]
Hi,
I can't find the steps with ICU.
don't understand if I need to compile ICU too or if I just need the tar.gz with .so / include files.
also, unclear what env variables need to be defined.
thanks.

**Comment by guillaumekln** [comment]
Hi,

We don't include the ICU installation steps since they depend on the system your are using.

On Ubuntu, the easiest is to install ICU from the package manager:

```text
sudo apt-get install libicu-dev
```

When ICU is installed on the system, there is no environment variables or flags to set.

**Comment by vince62s** [comment]
yes I figured it out.
after build there is an error (seg fault) when no "segment_alphabet" is set
setting to "Han" for instance will fix it.

**Comment by vince62s** [comment]
here is the output:
terminate called after throwing an instance of 'std::invalid_argument'
  what():  invalid Unicode script in segment_alphabet list: 
Aborted (core dumped)
