### ISSUE TITLE
Question about CMakeLists.txt's "create_library" condition

### ISSUE THREAD

**Issue by panosk** [OpenNMT/Tokenizer#300]
Hello,
I wanted to ask this for ages: What does this condition do exactly?

```CMake
if(COMMAND create_library)
  create_library(${PROJECT_NAME} SHARED ${SOURCES})
else()
  add_library(${PROJECT_NAME} SHARED ${SOURCES})
endif()
```
This prevents building the static library even when `BUILD_SHARED_LIBS` is set to `OFF`, so I have to change `SHARED` to `STATIC` in order to build the static lib.

**Comment by guillaumekln** [comment]
Ideally it should not appear here but `create_library` is an internal macro used in my company. You can just ignore this condition and focus on the else part.

Do you want to send a PR to fix static compilation? Should we just remove `SHARED` in `add_library`?
