### ISSUE TITLE
case annotation combined with other external features

### ISSUE THREAD

**Issue by vince62s** [OpenNMT/Tokenizer#312]
Let say I want to use both the Tokenizer case annotation and a custom script that adds POS tagging.

If I feed the Tokenizer with "This|PRON is|AUX an|DET example|NOUN" will it add the case annotation properly ? first /last ?

**Comment by guillaumekln** [comment]
Yes it works, and will add the case feature in the last position:

```python
>>> import pyonmttok
>>> tokenizer = pyonmttok.Tokenizer("space", case_feature=True)
>>> tokenizer.tokenize("This￨PRON is￨AUX an￨DET example￨NOUN")
(['this', 'is', 'an', 'example'], [['PRON', 'AUX', 'DET', 'NOUN'], ['C', 'L', 'L', 'L']])
```

However, when using the command line client the existing feature is also lowercase for some reason. This is not expected and should be fixed.

```text
$ echo "This|PRON is|AUX an|DET example|NOUN" | cli/tokenize --mode space --case_feature
this|pron￨M is|aux￨M an|det￨M example|noun￨M
```

**Comment by vince62s** [comment]
and it puts "M" everywhere

**Comment by guillaumekln** [comment]
Ah no, it actually works as expected. I used the wrong feature separator in the input.

```text
$ echo "This￨PRON is￨AUX an￨DET example￨NOUN" | cli/tokenize --mode space --case_feature
this￨PRON￨C is￨AUX￨L an￨DET￨L example￨NOUN￨L
```

**Comment by vince62s** [comment]
maybe adding this example in the doc would be nice.
