### ISSUE TITLE
C++ library's "tokenize" function causes application to hang with specific characters

### ISSUE THREAD

**Issue by NM-20** [OpenNMT/Tokenizer#315]
When passing strings with specific characters (i.e ©, bulletpoints, etc) to Tokenizer.tokenize in the C++ library, the containing application does not respond. I've ensured that it does not relate to the model I'm using ([OpenNMT-py English-German](https://s3.amazonaws.com/opennmt-models/transformer-ende-wmt-pyOnmt.tar.gz)) as well.

I've given the CLI client a shot, however, and it processes the string just fine, so it could also very well relate to how I have everything set up at the moment.

![image](https://user-images.githubusercontent.com/35472796/220777150-4f066087-8b7a-4bff-b443-1e8046e4c521.png)

**Comment by guillaumekln** [comment]
Can you share a code snippet and the compilation options that would reproduce this issue?

**Comment by NM-20** [comment]
> Can you share a code snippet and the compilation options that would reproduce this issue?

**Tokenizer Construction**

![image](https://user-images.githubusercontent.com/35472796/221028158-282688b2-d6ae-46b5-a0b1-ac710bb8f34c.png)

**Usage**

![image](https://user-images.githubusercontent.com/35472796/221028745-c274f8d0-9fa3-4c56-b4e4-d94bad2abccb.png)

```
/JMC /permissive- /Yu"pch.h" /MP /GS /W3 /Zc:wchar_t /ZI /Gm- /Od /sdl /Zc:inline /fp:precise /D "GW2RTT" /D "GW2RTT_EXPORTS" /D "USES_FBML_API" /D "_DEBUG" /D "_WINDOWS" /D "_USRDLL" /D "_CRT_SECURE_NO_WARNINGS" /D "_WINDLL" /D "_UNICODE" /D "UNICODE" /errorReport:prompt /WX- /Zc:forScope /RTC1 /Gd /MDd /std:c++20 /FC /EHsc /nologo /diagnostics:column 
```

I've noticed that the same issue occurs with [this CTranslate2 test I've made](https://github.com/NM-20/CTranslate2Test).

**Comment by guillaumekln** [comment]
In this example you are also running the translation. How do you know that the code is stuck in the tokenization step and not the translation?

Also, why do you need all these compilation flags? Can you reduce the flags to the minimum set that makes the compilation succeed?

**Comment by NM-20** [comment]
> In this example you are also running the translation. How do you know that the code is stuck in the tokenization step and not the translation?

I set breakpoints at and after `Tokenizer.tokenize`. The application never hits the second breakpoint.

> Also, why do you need all these compilation flags? Can you reduce the flags to the minimum set that makes the compilation succeed?

I'm using Visual Studio for the project, so I'm just using the comp flags it provides with some slight tweaks, but yes.

**Comment by NM-20** [comment]
I'm using ICU 72.1 on 1.36.0 right now. Do you think that may relate to this issue?

**Comment by guillaumekln** [comment]
No, that should not be an issue. I just updated the repository to use ICU 72.1 and all tests on all platforms are passing.

There may be an issue with your setup but I don’t know what. You should try debugging further and see where exactly it hangs.

**Comment by NM-20** [comment]
> No, that should not be an issue. I just updated the repository to use ICU 72.1 and all tests on all platforms are passing.
> 
> There may be an issue with your setup but I don’t know what. You should try debugging further and see where exactly it hangs.

Alright, I've managed to trace it down. It's occurring in `character_iterator`, from `Unicode.cc`, where it's ignoring the copyright character in the following string:
`"© 2016 Electronic Arts Inc."`

However, when it ignores this character, it does not advance the position, so it ends up infinitely looping over the input string and hanging execution, as seen here:
```c++
unsigned int char_size = 0;
code_point_t code_point = utf8_to_cp(
reinterpret_cast<const unsigned char*>(c_str), char_size);
if (code_point == 0)  // Ignore invalid code points.
	continue;
callback(c_str, char_size, code_point);
c_str += char_size;
```

Is there any particular reason as to why it does not advance the position?

Here is the call stack, if needed:
![image](https://user-images.githubusercontent.com/35472796/221292107-f4ca9e7c-5ee8-4a19-92cb-692a888fe68a.png)

**Comment by NM-20** [comment]
I'm not why this issue doesn't occur in the CLI client, though.

**Comment by guillaumekln** [comment]
This piece of code does look wrong. Thank you for tracing the execution. I don’t know why this wasn’t found before. The pointer should be advanced by at least 1 to avoid the infinite loop. Do you want to send a PR with the fix?

However, it does not explain why your valid input triggers this code path.

**Comment by NM-20** [comment]
No problem, and yes, I will submit a PR.

> However, it does not explain why your valid input triggers this code path.
Yeah that's what I'm concerned about. I just gave the Python API a shot and it works completely fine, despite using the same function through python binding. Tried tokenizing in C++ with the latest commit and still nothing.

**Comment by guillaumekln** [comment]
Maybe you have a memory error somewhere. Can you check for that? For example, are you sure this is correct?

```cpp
SetCurrentDirectoryA(FBML_GetGameDir().string().data());
```

`data()` may not include the final null character.

**Comment by NM-20** [comment]
> Maybe you have a memory error somewhere. Can you check for that? For example, are you sure this is correct?
> 
> ```c++
> SetCurrentDirectoryA(FBML_GetGameDir().string().data());
> ```
> 
> `data()` may not include the final null character.

Well, given that the same occurs in the example console app I made, I doubt this line has anything to do with it. But yes, I'll take a look.

**Comment by NM-20** [comment]
> Maybe you have a memory error somewhere. Can you check for that? For example, are you sure this is correct?
> 
> ```c++
> SetCurrentDirectoryA(FBML_GetGameDir().string().data());
> ```

Yes, it is correct. I tried adding another null terminator just to be safe, and the issue still happens.

As to any other potential memory errors, I did not find any in the example and the project I'm working on. Have you been able to reproduce this through the C++ library yourself?

**Comment by guillaumekln** [comment]
No, I'm not able to reproduce this issue. Here's the code snippet that I used:

```cpp
#include <iostream>
#include <onmt/Tokenizer.h>

int main() {
  onmt::Tokenizer tokenizer("source.spm");

  std::string text = "© 2023";
  std::vector<std::string> tokens;
  tokenizer.tokenize(text, tokens);

  for (const auto& token : tokens)
    std::cout << ' ' << token;
  std::cout << std::endl;
}
```
And I get the expected output when the current directory contains the SentencePiece model `source.spm`:
```text
 ▁© ▁2016 ▁Electronic ▁Arts ▁Inc .
```

Note that the CLI, the Python wrapper, and the unit tests are all using the C++ library. So it does not seem like there is an issue with the library.

**Comment by NM-20** [comment]
Hmm, the only potential culprit I've got left is the ICU library I'm using, because that's exactly where it's failing:
![image](https://user-images.githubusercontent.com/35472796/221445509-8a9a2c60-80d3-446a-a9c0-adcfbd15645a.png)

The U8_NEXT macro thinks the string is ill-formed, so maybe I didn't pick up the right 72.1 release archive or something. May I ask what release you downloaded?
![image](https://user-images.githubusercontent.com/35472796/221445630-623ee169-c6ce-49fb-bbe0-3f5b27eb00a9.png)

**Comment by guillaumekln** [comment]
I was using the ICU 70.1 package that is available in the Ubuntu 22.04 repository.

But I just tried compiling against `icu4c-72_1-Ubuntu22.04-x64.tgz` and `icu4c-72_1-src.tgz` (compiled from the source), and they all work as expected.

See also [this script](https://github.com/OpenNMT/Tokenizer/blob/master/bindings/python/tools/prepare_build_environment_windows.sh) that we use to compile the C++ library on Windows before building the Python wrapper.

**Comment by NM-20** [comment]
The script does not fix anything either. I've been debugging the expanded `U8_NEXT` macro in `Unicode.cc`, and found it to be failing here:

![image](https://user-images.githubusercontent.com/35472796/221752313-e77f755b-06c4-419a-8206-0ebbb732b502.png)

'©' (0xA9) is less than 0xC2, so it ends up assigning -1 to `c`. If possible, could you please send the expanded contents of the same macro as a code snippet? Just want to ensure there's no differences first, but I don't see why there would be in the first place.

**Comment by guillaumekln** [comment]
I'm not seeing the same macro in ICU release 72.1. `U8_NEXT` is defined here:

https://github.com/unicode-org/icu/blob/release-72-1/icu4c/source/common/unicode/utf8.h#L352

which is then resolved to:

https://github.com/unicode-org/icu/blob/release-72-1/icu4c/source/common/unicode/utf8.h#L381-L407

**Comment by NM-20** [comment]
If you are referring to the formatting, those are just some tweaks I made to make it a bit more readable. By default, the expanded macro looks like this:
![image](https://user-images.githubusercontent.com/35472796/222002823-338f483c-0644-438a-94fd-4f8fe08e4bd7.png)

I did a quick separation of some of the conditions, and confirmed that it is indeed failing at `(c) >= 0xc2`.
![image](https://user-images.githubusercontent.com/35472796/222003253-6f509677-c3b7-4036-8ac8-8309b67754fa.png)

Could you check which code path the macro takes on your system?

**Comment by guillaumekln** [comment]
> '©' (0xA9) is less than 0xC2

Actually © is 2 bytes in UTF-8: 0xC2 0xA9

So I think your input text/file is encoded in UTF-16 or UTF-32, but the tokenizer expects the input to be encoded in UTF-8. Can you check for that?

If I convert my input text to UTF-16 I can reproduce the original issue with version 1.36.0 (so before the infinite loop fix).

**Comment by NM-20** [comment]
> So I think your input text/file is encoded in UTF-16 or UTF-32, but the tokenizer expects the input to be encoded in UTF-8. Can you check for that?

I just gave that a shot, and I'm happy to say it worked! It seems like UTF-8 with a byte-order mark (the encoding I was using) does cause issues with the tokenizer, as switching to UTF-8 without a signature fixed it.

The output at the moment, though, does not display the tokenized copyright symbol correctly. This is what it looks like:

**Tokenized**
![image](https://user-images.githubusercontent.com/35472796/222265846-d771deae-81e0-428e-9f28-1eb3a0af3cee.png)

**Detokenized**
![image](https://user-images.githubusercontent.com/35472796/222265670-12c08c61-2271-4f4c-9506-36ffa77da4d6.png)

**Comment by NM-20** [comment]
This does solve the issue for constant string literals, but strings that are not constant still remain as an issue. I have a rather "unique" use case for this library at the moment; I've been using it within a game. Specifically, I have written a DLL, which gets loaded into the game at runtime. The DLL then hooks some functions that retrieve strings, and translates them before returning them. As a result, I do not have access to the strings outside of runtime, and so a UTF-8 file encoding will do nothing. I've tried using MultiByteToWideChar, then WideCharToMultiByte to get a UTF-8 string (and it does work) but it feels like more of a hack, if anything.

Do you know of any other ways I can get a UTF-8 string for tokenization, ideally without any other external dependencies?

**Comment by guillaumekln** [comment]
> The output at the moment, though, does not display the tokenized copyright symbol correctly. This is what it looks like:

As far as I know this is an issue with the Windows console and UTF-8 strings. See this issue: https://github.com/OpenNMT/Tokenizer/issues/308

> Do you know of any other ways I can get a UTF-8 string for tokenization, ideally without any other external dependencies?

I don't know the details of your application and where exactly you get those strings. You just need to ensure they are UTF-8 encoded. There could be a parameter in the library that produces these strings to change the encoding, or you should use whatever functions that can convert them correctly (such as `WideCharToMultiByte`).

**Comment by NM-20** [comment]
> The output at the moment, though, does not display the tokenized copyright symbol correctly. This is what it looks like:

Alright, the solution there did indeed fix it.

> I don't know the details of your application and where exactly you get those strings. You just need to ensure they are UTF-8 encoded. There could be a parameter in the library that produces these strings to change the encoding, or you should use whatever functions that can convert them correctly (such as WideCharToMultiByte).

Yeah, I'll just stick with `WideCharToMultiByte`. I do believe that the tokenizer's requirement for UTF-8 input should be mentioned somewhere, so as to prevent another situation akin to this.

Thank you so much for your assistance throughout this!
