### ISSUE TITLE
my source file doesn't compile

### ISSUE THREAD

**Issue by AESTheProgrammer** [OpenNMT/Tokenizer#325]
#include <iostream>
#include <ostream>
#include <vector>
#include <onmt/Tokenizer.h>

int main() {
    onmt::Tokenizer tokenizer(onmt::Tokenizer::Mode::Conservative, onmt::Tokenizer::Flags::JoinerAnnotate);
    std::vector<std::string> tokens;
    tokenizer.tokenize("Hello World!", tokens);
    const std::string joiner_marker = "￭";
    std::cout << joiner_marker << '\n';
    //std::cout <<  tokens[0] << "\n";
}

/usr/bin/ld: CMakeFiles/MyTestFile.dir/my_test.cpp.o: warning: relocation against `_ZN4onmt9Tokenizer13joiner_markerB5cxx11E' in read-only section `.text.startup'
/usr/bin/ld: CMakeFiles/MyTestFile.dir/my_test.cpp.o: in function `onmt::Tokenizer::~Tokenizer()':
my_test.cpp:(.text._ZN4onmt9TokenizerD2Ev[_ZN4onmt9TokenizerD5Ev]+0x9): undefined reference to `vtable for onmt::Tokenizer'
/usr/bin/ld: CMakeFiles/MyTestFile.dir/my_test.cpp.o: in function `main':
my_test.cpp:(.text.startup+0x65): undefined reference to `onmt::Tokenizer::joiner_marker[abi:cxx11]'
/usr/bin/ld: my_test.cpp:(.text.startup+0x75): undefined reference to `onmt::Tokenizer::Tokenizer(onmt::Tokenizer::Mode, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)'
/usr/bin/ld: my_test.cpp:(.text.startup+0xe9): undefined reference to `onmt::ITokenizer::tokenize(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, bool) const'
/usr/bin/ld: CMakeFiles/MyTestFile.dir/my_test.cpp.o: in function `onmt::Tokenizer::~Tokenizer()':
my_test.cpp:(.text._ZN4onmt9TokenizerD0Ev[_ZN4onmt9TokenizerD5Ev]+0x9): undefined reference to `vtable for onmt::Tokenizer'
/usr/bin/ld: warning: creating DT_TEXTREL in a PIE
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/MyTestFile.dir/build.make:97: MyTestFile] Error 1
make[1]: *** [CMakeFiles/Makefile2:246: CMakeFiles/MyTestFile.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

**Comment by guillaumekln** [comment]
Please post how you are compiling and linking against the Tokenizer.

**Comment by AESTheProgrammer** [comment]
my problem was solved.
