### ISSUE TITLE
How to develop a C++ tokenizer for MarianMT using the OpenNMT Tokenizer

### ISSUE THREAD

**Issue by Zapotecatl** [OpenNMT/Tokenizer#326]
Hi,
My intention is to develop a C++ project that runs the MarianMT (onnx) model to translate from Spanish to English: https://huggingface.co/Helsinki-NLP/opus-mt-es-en. However, I'm stuck on how to proceed about the tokenizer.

**It is possible to use the OpenNMT Tokenizer with MarianMT from Spanish to English?** That is, where to use the files: source.spm, target.spm, vocab.json and tokenizer_config.json

I know that perhaps the question is very open, any guide or idea is welcome, thank you very much!

**Comment by guillaumekln** [comment]
Hi,

`source.spm` and `target.spm` are SentencePiece models so you could either use the [SentencePiece library](https://github.com/google/sentencepiece) directly or the OpenNMT Tokenizer. For the latter you can find a SentencePiece usage example in this test case:

https://github.com/OpenNMT/Tokenizer/blob/1bc1231297d9e18386cdfce89a47c8c59458c22b/test/test.cc#L966-L973

For C++ execution of the MarianMT model you should also consider [CTranslate2](https://github.com/OpenNMT/CTranslate2/) which would typically be better and faster than ONNX. This is a different topic though.

**Comment by Zapotecatl** [comment]
Hi @guillaumekln ,

Thanks for your answer!

I tried your first suggestion, I used the sentencepiece library directly (I built the static library and configured it in my visual studio). I used the source.spm file as the model. My program and output is this:

```
#include <iostream>
#include <sentencepiece_processor.h>
int main()
{
    sentencepiece::SentencePieceProcessor processor;
    const auto status = processor.Load("D:\\SentencePiece\\source.spm");

    if (!status.ok()) {
        std::cerr << status.ToString() << std::endl;
        // error
    }
   
    std::vector<std::string> pieces;
    processor.Encode("Hola mi amor", &pieces);
    for (const std::string& token : pieces) {
        std::cout << token << std::endl;
    }

    std::vector<int> ids;
    processor.Encode("Hola mi amor", &ids);
    for (const int id : ids) {
        std::cout << id << std::endl;
    }
}
```
Output

```
ÔûüHola
Ôûümi
Ôûüamor
868
64
866
```
Which apparently tokenizes correctly. However, my problem is with the ids. My python program delivers the correct ids.

```
from transformers import AutoTokenizer, MarianMTModel

src = "es"  # source language
trg = "en"  # target language
model_name = f"Helsinki-NLP/opus-mt-{src}-{trg}"
model = MarianMTModel.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)

sample_text = "Hola mi amor"
batch = tokenizer([sample_text], return_tensors="pt")
print(batch)
```
Output

`{'input_ids': tensor([[2119,  155, 1821,    0]]), 'attention_mask': tensor([[1, 1, 1, 1]])}`

I'm probably interpreting something wrong? I understand that I have strayed from a directly related topic on OpenNMT, so I really appreciate your response.

**Comment by guillaumekln** [comment]
Since you are using SentencePiece directly, your issue is no longer related to the OpenNMT Tokenizer. You should ask in the SentencePiece repo.
