### ISSUE TITLE
feeling like supporting jieba ?

### ISSUE THREAD

**Issue by vince62s** [OpenNMT/Tokenizer#35]
Hello team,
wouldn't it be good to support Jieba natively ?

https://github.com/fxsjy/jieba

cheers.

**Comment by guillaumekln** [comment]
Hi,

I don't think this will happen unless they provide a shared native library that we can link to.

**Comment by guillaumekln** [comment]
Found this implementation: https://github.com/yanyiwu/cppjieba

How often is it used for Chinese segmentation? What are the alternatives?

**Comment by vince62s** [comment]
we don't use it in fact.
@Zenglinxiao can elaborate a bit maybe.

**Comment by Zenglinxiao** [comment]
Jieba is a popular Chinese segmentation tool and is widely used in many cases. It is fast But as it is too old, there are many alternatives gives better results based on some more advanced algorithm. In NMT, there is no one uses JIEBA as segmentation tool according to the previous year's WMT top submission.
We've tested Jieba, THULAC & Pkuseg. Among these three, Pkuseg gives the best results. 
Maybe Pkuseg or THULAC is worth supporting.

**Comment by guillaumekln** [comment]
Ok thanks, so I think we can close this issue for now.
