### ISSUE TITLE
erro when building

### ISSUE THREAD

**Issue by vince62s** [OpenNMT/Tokenizer#39]
sudo apt install libgtest-dev
does not solve it.

cmake -DCMAKE_BUILD_TYPE=Release ..
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found sentencepiece: /usr/local/lib/libsentencepiece.so
-- Found sentencepiece_train: /usr/local/lib/libsentencepiece_train.so
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   program_options
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_MAIN_LIBRARY) 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/moses/onmt_tokenizer/build

**Comment by guillaumekln** [comment]
Note that Google Test is only required if you want to compile the test binary.

To solve the actual issue, it looks like `libgtest-dev` does not come with prebuilt libraries. Maybe it's best to manually compile the [latest release](https://github.com/google/googletest/releases) and set `-DGTEST_ROOT` when running `cmake`.
