### ISSUE TITLE
Install pyonmttok on macOS?

### ISSUE THREAD

**Issue by panosk** [OpenNMT/Tokenizer#42]
Hi,

I'm trying to install on macOS but it fails with the message

`Could not find a version that satisfies the requirement pyonmttok (from versions: )`

I have macOS's python2.7 and homebrew python3.7. Searching with pip finds the package though.

**Comment by guillaumekln** [comment]
The [Python wheels](https://pypi.org/project/pyonmttok/#files) are only available for Linux at moment.

I don't have a clear plan to add support for Mac OS as I don't have access to this environment. A first step would be to adapt the [build script](https://github.com/OpenNMT/Tokenizer/blob/master/bindings/python/tools/build_wheel.sh). I see that Travis has a Mac OS environment, let's if that could be solution.

**Comment by jsenellart** [comment]
@panosk, experimentally I pushed a wheel for macOS based on latest revision, boost 1.67 and python 2.7 (pyonmttok-1.10.0-cp27-cp27m-macosx_10_13_x86_64.whl) - could you check if it works for you?

**Comment by guillaumekln** [comment]
The wheel is missing the shared libraries that it depends on. On OSX, one should use [`delocate`](https://pypi.org/project/delocate/) to list the required shared libraries and inject them in the wheel.

For reference, here is the content of the Linux wheel (wheels are just zip files):

```
.
├── pyonmttok
│   ├── __init__.py
│   ├── .libs
│   │   ├── libboost_python27-4e9f47d7.so.1.67.0
│   │   ├── libOpenNMTTokenizer-a00e18a4.so
│   │   ├── libsentencepiece-7e59d198.so.0.0.0
│   │   └── libsentencepiece_train-9897f172.so.0.0.0
│   └── tokenizer.so
└── pyonmttok-1.10.0.dist-info
    ├── METADATA
    ├── RECORD
    ├── top_level.txt
    └── WHEEL
```

**Comment by jsenellart** [comment]
fixed by #43 - I pushed wheels on PyPI. @panosk - can you check they work for you (support 2.7 and 3.7)

**Comment by panosk** [comment]
@jsenellart 
It installs fine for python 2.7, for python 3.7 I'm not able to install with pip, I get the same message as in my initial post. Could be something messy with my setup though, and if so I'll let you know. Thanks!

**Comment by jsenellart** [comment]
mmm... strange - could you try the following:
- download manually the wheel:
https://files.pythonhosted.org/packages/5c/c6/cea2e530e9a2562d1e8010551a6e58543aa6b508250d3fbc261bdd463496/pyonmttok-1.10.1-cp37-cp37m-macosx_10_9_x86_64.whl
- install manually `pip install pyonmttok-1.10.1-cp37-cp37m-macosx_10_9_x86_64.whl`

**Comment by panosk** [comment]
Nope, it won’t install, I get:

"…is not a supported wheel on this platform”

Just to make sure, I switched python versions temporarily, so now `python -V` outputs `Python 3.7.0`.

**Comment by guillaumekln** [comment]
Let's reopen this one as MacOS packages were not pushed in a long time. Any new solution should be integrated in the project CI.

**Comment by panosk** [comment]
Hi @guillaumekln ,

I can install and use just fine version 1.18.2 with pip and Python 3.7.6 on macOS Catalina (10.15.2), so I guess this is solved :)

**Comment by guillaumekln** [comment]
Ah? So during installation it grabs the wheel `pyonmttok-1.18.2-cp37-cp37m-manylinux1_x86_64.whl` and then it runs just fine?

**Comment by panosk** [comment]
No, apologies, my bad. The version is `pyonmttok-1.10.1-cp37-cp37m-macosx_10_9_x86_64.whl`
```
pyonmttok (1.18.2)  - OpenNMT tokenization library
  INSTALLED: 1.10.1
  LATEST:    1.18.2
```

**Comment by filips123** [comment]
@guillaumekln @jsenellart I'm trying to automate building wheels on GitHub Actions with `cibuildwheel`, but I currently have some problems with it. Could you check it. Details are in #136.
