### ISSUE TITLE
Compilation errors on Windows/Visual Studio

### ISSUE THREAD

**Issue by jhnwnd** [OpenNMT/Tokenizer#50]
tokenizer\src\tokenizer.cc(157): error C2065: 'ssize_t': undeclared identifier

ssize_t is not standard C++. Can this code be refactored or else something like this be added to the top of the file:
#ifdef _MSC_VER
  #include <BaseTsd.h>
  typedef SSIZE_T ssize_t;
#endif

**Comment by guillaumekln** [comment]
This was a small change so a pushed a quick fix. Thanks.
