### ISSUE TITLE
Detokenization doesn't behave as the inverse of tokenize?

### ISSUE THREAD

**Issue by fpug** [OpenNMT/Tokenizer#62]
If I run this in python3, latest version of the library:

> import pyonmttok
> 
> tokenizer = pyonmttok.Tokenizer('conservative')
> 
> input_text = "It costs £2,000"
> print(input_text)
> 
> tokens, features = tokenizer.tokenize(input_text)
> output_text = tokenizer.detokenize(tokens)
> 
> print(output_text)

I get:

> It costs £2,000
> It costs £ 2,000

Shouldn't the two lines be equal?

**Comment by guillaumekln** [comment]
By default, it generates a non reversible tokenization. See this section of the documentation for ways to make it reversible:

https://github.com/OpenNMT/Tokenizer/blob/master/docs/options.md#marking-joint-tokens

**Comment by fpug** [comment]
Thanks!  I take the chance to signal that when in the python library the parameter mode is passed as named (as in, mode='conservative') it causes a segmentation fault.

**Comment by guillaumekln** [comment]
Interesting, thanks I will fix that.
