### ISSUE TITLE
Combining SPM with source_features

### ISSUE THREAD

**Issue by Stamenov** [OpenNMT/Tokenizer#76]
I am trying to combine a Sentencepiece tokenization model with source features, such as casing features, for an OpenNMT-tf NMT model. 

I am in a way attempting to mimic the performance of OpenNMT-lua and its tokenization and source features.

So my question is:

1. It is reasonable at all to use Sentencepiece with casing features, as OpenNMT Tokenizer has its own BPE algorithm.

2. Assuming it is reasonable, how do I combine the OpenNMT Tokenizer casing feature with the SPM model. Do I train it separately as normal and just do something similar to the following:

`$ echo "Hello world!" | cli/tokenize --case_feature --mode none --sp_model_path spm.model`

or should I somehow combine the case features while training the SPM, since I guess I might want to train it on lowercased data?

**Comment by guillaumekln** [comment]
1. Not sure it will be better but it is a valid use case.
2. This command line should work as expected. The SentencePiece model will be applied on **truecased data** and then the Tokenizer will do an additional pass to lowercase tokens and attach case information.

If you train your SentencePiece model on lowercased data, the only option at the moment is to use [`case_markup`](https://github.com/OpenNMT/Tokenizer/blob/master/docs/options.md#case_markup-boolean-default-false) as it is applied before calling SentencePiece while `case_features` is applied after.
