### ISSUE TITLE
AttributeError: module 'pyonmttok' has no attribute 'BPELearner'

### ISSUE THREAD

**Issue by ymoslem** [OpenNMT/Tokenizer#81]
Hello!

I am using the Python version of pyonmttok. The Tokenizer works fine.

However, when I tried `BPELearner()` as illustrated in ReadMe file:
`learner = pyonmttok.BPELearner(tokenizer=tokenizer, symbols=32000)`

I get an error message:
`AttributeError: module 'pyonmttok' has no attribute 'BPELearner'`

I am not sure if this is relevant; I am on Mac OS, Python 3.6.0, and when I checked the version I have, it is pyonmttok==1.10.1

When I tried to upgrade, it says:
`Requirement already up-to-date: pyonmttok in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (1.10.1)`

When I tried to force pyonmttok==1.14.0, it says:
`ERROR: No matching distribution found for pyonmttok==1.14.0`

Thanks!

**Comment by guillaumekln** [comment]
Subword learning APIs were introduced in 1.12.0 but 1.10.1 is the latest version that was built for macOS, see #42.

Unfortunately we don't have a process to release macOS compatible wheels at the moment. As mentioned in the issue, we should be able to do that with Travis that provides a macOS environment. I will accept a PR in that directory.

**Comment by guillaumekln** [comment]
I will close this one in favor of #42.
