### ISSUE TITLE
Can't tokenize with SentencePiece model anymore.

### ISSUE THREAD

**Issue by francoishernandez** [OpenNMT/Tokenizer#82]
Hi @guillaumekln 

I may be doing something wrong, but I can't tokenize properly with a SentencePiece model.

Following the basic usage from the docs:

```
Tokenizer/test/data/sp-models$ echo "The two shows, called Desire and Secrets, will be one-hour prime-time shows." | ../../../build/cli/tokenize --mode none -sp_model_path sp.model
The two shows, called Desire and Secrets, will be one-hour prime-time shows.
```

When spm gives:

```
Tokenizer/test/data/sp-models$ echo "The two shows, called Desire and Secrets, will be one-hour prime-time shows." | spm_encode --model=sp.model --output_format=piece
The ▁two ▁shows , ▁called ▁De si re ▁and ▁S e c re t s , ▁will ▁be ▁one - hour ▁prime - time ▁shows .
```

Did something change recently?

Thanks!
François

**Comment by guillaumekln** [comment]
Hi @francoishernandez,

`-sp_model_path` should be `--sp_model` on the command line, see `cli/tokenize -h`. (Not sure why it does not complain here.)

The documentation uses the names from the Python API. We should probably update to command line to make sure all names from the documentation are accepted.

**Comment by francoishernandez** [comment]
Oh ok. Works fine with the proper flag indeed.
Thanks!
