### ISSUE TITLE
iostream error while loading the tokenizer (pyonmttok) 

### ISSUE THREAD

**Issue by kishorguptha** [OpenNMT/Tokenizer#85]
Hi,
  
    I am trying to run the OpenNMT server on my local machine for testing GER-ENG model for
language translation.   While I run the server on my local machine with the below parameters,
I get the below error message: 
**RuntimeError: basic_filebuf::underflow error reading the file: iostream error**

Please find the complete log of error below:
**OpenNMT/OpenNMT-py$ python3 server.py --ip "0.0.0.0"  --port "7790" --url_root "/translator"  --config  "./available_models/conf_pyonmttok.json" 
Pre-loading model 1
[2019-07-30 13:40:27,078 INFO] Loading model 1
[2019-07-30 13:40:37,618 INFO] Loading tokenizer
Traceback (most recent call last):
  File "server.py", line 123, in <module>
    debug=args.debug)
  File "server.py", line 24, in start
    translation_server.start(config_file)
  File "/home/administrator/OpenNMT/OpenNMT-py/onmt/translate/translation_server.py", line 102, in start
    self.preload_model(opt, model_id=model_id, **kwargs)
  File "/home/administrator/OpenNMT/OpenNMT-py/onmt/translate/translation_server.py", line 140, in preload_model
    model = ServerModel(opt, model_id, **model_kwargs)
  File "/home/administrator/OpenNMT/OpenNMT-py/onmt/translate/translation_server.py", line 227, in __init__
    self.load()
  File "/home/administrator/OpenNMT/OpenNMT-py/onmt/translate/translation_server.py", line 319, in load
    tokenizer = pyonmttok.Tokenizer(mode, **tokenizer_params)
RuntimeError: basic_filebuf::underflow error reading the file: iostream error
OpenNMT/OpenNMT-py$** 

Could you please assist me in resolving this issue ?

Thank You,
Kishor.

**Comment by guillaumekln** [comment]
Can you post your tokenization configuration?

**Comment by kishorguptha** [comment]
Please find the config file:
{
    "models_root": "./available_models",
    "models": [
        {
            "id": 1,
            "model": "iwslt-brnn2.s131_acc_62.71_ppl_7.74_e20.pt",
            "timeout": 600,
            "on_timeout": "to_cpu",
            "load": true,
            "opt": {
                "gpu": -1,
                "beam_size": 5
            },
            "tokenizer": {
                "type": "pyonmttok",
                "mode": "str",
                "params": {
                    "bpe_model_path":"",
                    "vocabulary_path":"",
                    "vocabulary_threshold":0,
                    "sp_model_path":"",
                    "sp_nbest_size":0,
                    "sp_alpha":0.1,
                    "joiner":"￭",
                    "joiner_annotate":false,
                    "joiner_new":false,
                    "spacer_annotate":false,
                    "spacer_new":false,
                    "case_feature":false,
                    "case_markup":false,
                    "no_substitution":false,
                    "preserve_placeholders":false,
                    "preserve_segmented_tokens":false,
                    "segment_case":false,
                    "segment_numbers":false,
                    "segment_alphabet_change":false,
                    "segment_alphabet":[]                    
                }
            }
        },{
            "model": "model_0.light.pt",
            "timeout": -1,
            "on_timeout": "unload",
            "model_root": "../other_models",
            "opt": {
                "batch_size": 1,
                "beam_size": 10
            }
        }
    ]
}

**Comment by guillaumekln** [comment]
"str" is not a valid tokenization mode, see the [documentation](https://github.com/OpenNMT/Tokenizer/blob/master/docs/options.md#mode-string-required). And you should probably clean it up, you don't need to define all arguments. Try first:

```json
"tokenizer": {
  "type": "pyonmttok",
  "mode": "conservative"
}
```

**Comment by kishorguptha** [comment]
Okay...let me try this first. Thank you for the prompt reply..

**Comment by kishorguptha** [comment]
Thank you very much the issue got resolved with the below  config file:

{
    "models_root": "./available_models",
    "models": [
        {
            "id": 1,
            "model": "iwslt-brnn2.s131_acc_62.71_ppl_7.74_e20.pt",
            "timeout": 600,
            "on_timeout": "to_cpu",
            "load": true,
            "opt": {
                "gpu": -1,
                "beam_size": 5
            },
            "tokenizer": {
                "type": "pyonmttok",
                "mode": "conservative",
                "params": {
                    "vocabulary_threshold":0,
                    "sp_nbest_size":0,
                    "sp_alpha":0.1,
                    "joiner":"￭",
                    "joiner_annotate":false,
                    "joiner_new":false,
                    "spacer_annotate":false,
                    "spacer_new":false,
                    "case_feature":false,
                    "case_markup":false,
                    "no_substitution":false,
                    "preserve_placeholders":false,
                    "preserve_segmented_tokens":false,
                    "segment_case":false,
                    "segment_numbers":false,
                    "segment_alphabet_change":false,
                    "segment_alphabet":[]                    
                }
            }
        },{
            "model": "model_0.light.pt",
            "timeout": -1,
            "on_timeout": "unload",
            "model_root": "../other_models",
            "opt": {
                "batch_size": 1,
                "beam_size": 10
            }
        }
    ]
}
