### ISSUE TITLE
Remove punctuation 

### ISSUE THREAD

**Issue by amallia** [OpenNMT/Tokenizer#90]
I was wondering if there is an obvious way to tokenize and discard punctuation.

**Comment by guillaumekln** [comment]
There is no option for that. Could you simply do that as a postprocessing step?

**Comment by amallia** [comment]
Yes I would, but it would be nice if it could be included in the library as an option

**Comment by guillaumekln** [comment]
Could you tell in what type of application it is common to remove punctuation?

**Comment by amallia** [comment]
Text search is an example. You don’t want to index punctuation

**Comment by guillaumekln** [comment]
Thanks for the request. Let's keep this issue open so that we can think a bit more about it. As it is specific to a use case and easily done in a postprocessing step, I'm not sure it fits in the scope of this project.

**Comment by guillaumekln** [comment]
I'm going to close this issue since it is unlikely we will add an option for that. This is best done in a postprocessing step.
